# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd9f08f9e8fd7d7df34b17109cf9a6544a89214a4b81be837773fc2d8a655a36c786a0b9d7452a44a468fd901ba80bfe7b213f1f2809a35b671ea197dea9e9b

test:
  secret_key_base: d48c21b47a3449ea838fd2561581dc32c006d5372f4262bbfdf26917d84672c20d1b7a59d7d8b44b0cd5a14a8445bf1ac8b40529758be062a921f1cf2b88f706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
